version: "3"
services:
  postgres:
    build:
      context: .
      dockerfile: ./db/db.dockerfile 
    image: "reels-db"
    container_name: "reels-db" 
    environment:
      POSTGRES_DB: "reels"
      POSTGRES_USER: "reels"
      POSTGRES_PASSWORD: "reels" 
      PGDATA: "/data/reels"
    volumes:
       - reels:/data/reels
    networks:
       - db-subnet 
    ports:
      - "5432:5432"
    restart: unless-stopped
  api:
      build:
        context: .
        dockerfile: ./api/api.dockerfile
      image: "reels-api"
      container_name: "reels-api"
      environment:
        DB_HOSTNAME: "reels-db"
        DB_USER: "reels"
        DB_PASSWORD: "reels" 
        DB_PORT: 5432
        DB_NAME: "reels"
      networks:
         - db-subnet 
      ports:
        - "5050:5050"
      restart: unless-stopped
volumes:
  reels:
    external: true
networks:
  db-subnet:
    internal: true

